(set-info :source |printed by MathSAT|)
(declare-fun |.x{14}| () (Array Int Int))
(declare-fun |.x{18}| () (Array Int Int))
(declare-fun |.x{15}| () (Array Int Int))
(declare-fun |.x{19}| () (Array Int Int))
(declare-fun |.x{16}| () Int)
(declare-fun |.x{20}| () Int)
(declare-fun |.x{17}| () Int)
(declare-fun |.x{21}| () Int)
(declare-fun |.loc{2}| () Bool)
(declare-fun |.loc{3}| () Bool)
(declare-fun |.x{9}| () Int)
(declare-fun |.x{34}| () Int)
(define-fun .def_12 () Int (! |.x{16}| :next |.x{20}|))
(define-fun .def_59 () Bool (= .def_12 0))
(define-fun .def_16 () Bool (! |.loc{2}| :next |.loc{3}|))
(define-fun .def_28 () Bool (not .def_16))
(define-fun .def_60 () Bool (! (and .def_28 .def_59) :init true))
(define-fun .def_14 () Int (! |.x{17}| :next |.x{21}|))
(define-fun .def_57 () Bool (= .def_14 |.x{21}|))
(define-fun .def_10 () (Array Int Int) (! |.x{15}| :next |.x{19}|))
(define-fun .def_53 () Bool (= .def_10 |.x{19}|))
(define-fun .def_8 () (Array Int Int) (! |.x{14}| :next |.x{18}|))
(define-fun .def_50 () Bool (= .def_8 |.x{18}|))
(define-fun .def_47 () Bool (= |.x{20}| 0))
(define-fun .def_34 () Bool (<= .def_14 .def_12))
(define-fun .def_48 () Bool (and .def_34 .def_47))
(define-fun .def_49 () Bool (and .def_28 .def_48))
(define-fun .def_51 () Bool (and .def_49 .def_50))
(define-fun .def_38 () Int (select .def_8 .def_12))
(define-fun .def_40 () Int (+ .def_38 1))
(define-fun .def_41 () (Array Int Int) (store .def_8 .def_12 .def_40))
(define-fun .def_42 () Bool (= |.x{18}| .def_41))
(define-fun .def_43 () Bool (and .def_16 .def_42))
(define-fun .def_30 () Int (* (- 1) |.x{20}|))
(define-fun .def_31 () Int (+ .def_12 .def_30))
(define-fun .def_32 () Bool (= .def_31 (- 1)))
(define-fun .def_44 () Bool (and .def_32 .def_43))
(define-fun .def_35 () Bool (not .def_34))
(define-fun .def_45 () Bool (and .def_35 .def_44))
(define-fun .def_52 () Bool (or .def_45 .def_51))
(define-fun .def_54 () Bool (and .def_52 .def_53))
(define-fun .def_55 () Bool (and |.loc{3}| .def_54))
(define-fun .def_24 () Int (* (- 1) |.x{9}|))
(define-fun .def_25 () (Array Int Int) (store .def_10 .def_12 .def_24))
(define-fun .def_26 () Bool (= |.x{19}| .def_25))
(define-fun .def_21 () Bool (not |.loc{3}|))
(define-fun .def_19 () (Array Int Int) (store .def_8 .def_12 |.x{9}|))
(define-fun .def_20 () Bool (= |.x{18}| .def_19))
(define-fun .def_22 () Bool (and .def_20 .def_21))
(define-fun .def_27 () Bool (and .def_22 .def_26))
(define-fun .def_29 () Bool (and .def_27 .def_28))
(define-fun .def_33 () Bool (and .def_29 .def_32))
(define-fun .def_36 () Bool (and .def_33 .def_35))
(define-fun .def_56 () Bool (or .def_36 .def_55))
(define-fun .def_58 () Bool (! (and .def_56 .def_57) :trans true))
(define-fun .def_61 () Int (! |.x{34}| :next |.xpv{1}|))
(define-fun .def_68 () Bool (<= .def_61 0))
(define-fun .def_69 () Bool (not .def_68))
(define-fun .def_70 () Bool (and .def_34 .def_69))
(define-fun .def_66 () Bool (<= .def_14 .def_61))
(define-fun .def_67 () Bool (not .def_66))
(define-fun .def_71 () Bool (and .def_67 .def_70))
(define-fun .def_62 () Int (select .def_8 .def_61))
(define-fun .def_63 () Int (select .def_10 .def_61))
(define-fun .def_64 () Bool (<= .def_63 .def_62))
(define-fun .def_65 () Bool (not .def_64))
(define-fun .def_72 () Bool (and .def_65 .def_71))
(define-fun .def_73 () Bool (and .def_16 .def_72))
(define-fun .def_75 () Bool (! (not .def_73) :invar-property 0))
(assert true)
