(set-info :source |printed by MathSAT|)
(declare-fun |.x{10}| () (Array Int Int))
(declare-fun |.x{13}| () (Array Int Int))
(declare-fun |.x{11}| () Int)
(declare-fun |.x{14}| () Int)
(declare-fun |.x{12}| () Int)
(declare-fun |.x{15}| () Int)
(declare-fun |.loc{2}| () Bool)
(declare-fun |.loc{3}| () Bool)
(declare-fun |.x{25}| () Int)
(define-fun .def_10 () Int (! |.x{11}| :next |.x{14}|))
(define-fun .def_48 () Bool (= .def_10 0))
(define-fun .def_14 () Bool (! |.loc{2}| :next |.loc{3}|))
(define-fun .def_23 () Bool (not .def_14))
(define-fun .def_49 () Bool (! (and .def_23 .def_48) :init true))
(define-fun .def_12 () Int (! |.x{12}| :next |.x{15}|))
(define-fun .def_46 () Bool (= .def_12 |.x{15}|))
(define-fun .def_8 () (Array Int Int) (! |.x{10}| :next |.x{13}|))
(define-fun .def_39 () Bool (= .def_8 |.x{13}|))
(define-fun .def_17 () Bool (<= .def_12 .def_10))
(define-fun .def_40 () Bool (and .def_17 .def_39))
(define-fun .def_38 () Bool (= |.x{14}| 0))
(define-fun .def_41 () Bool (and .def_38 .def_40))
(define-fun .def_42 () Bool (and .def_23 .def_41))
(define-fun .def_30 () Int (select .def_8 .def_10))
(define-fun .def_31 () Int (+ .def_10 .def_30))
(define-fun .def_32 () (Array Int Int) (store .def_8 .def_10 .def_31))
(define-fun .def_33 () Bool (= |.x{13}| .def_32))
(define-fun .def_18 () Bool (not .def_17))
(define-fun .def_34 () Bool (and .def_18 .def_33))
(define-fun .def_35 () Bool (and .def_14 .def_34))
(define-fun .def_26 () Int (* (- 1) |.x{14}|))
(define-fun .def_27 () Int (+ .def_10 .def_26))
(define-fun .def_28 () Bool (= .def_27 (- 1)))
(define-fun .def_36 () Bool (and .def_28 .def_35))
(define-fun .def_43 () Bool (or .def_36 .def_42))
(define-fun .def_44 () Bool (and |.loc{3}| .def_43))
(define-fun .def_20 () (Array Int Int) (store .def_8 .def_10 .def_10))
(define-fun .def_21 () Bool (= |.x{13}| .def_20))
(define-fun .def_16 () Bool (not |.loc{3}|))
(define-fun .def_19 () Bool (and .def_16 .def_18))
(define-fun .def_22 () Bool (and .def_19 .def_21))
(define-fun .def_24 () Bool (and .def_22 .def_23))
(define-fun .def_29 () Bool (and .def_24 .def_28))
(define-fun .def_45 () Bool (or .def_29 .def_44))
(define-fun .def_47 () Bool (! (and .def_45 .def_46) :trans true))
(define-fun .def_50 () Int (! |.x{25}| :next |.xpv{1}|))
(define-fun .def_60 () Bool (<= .def_50 0))
(define-fun .def_61 () Bool (not .def_60))
(define-fun .def_62 () Bool (and .def_17 .def_61))
(define-fun .def_58 () Bool (<= .def_12 .def_50))
(define-fun .def_59 () Bool (not .def_58))
(define-fun .def_63 () Bool (and .def_59 .def_62))
(define-fun .def_51 () Int (select .def_8 .def_50))
(define-fun .def_52 () Int (* (- 1) .def_51))
(define-fun .def_54 () Int (* 2 .def_50))
(define-fun .def_56 () Int (+ .def_54 .def_52))
(define-fun .def_57 () Bool (<= 0 .def_56))
(define-fun .def_64 () Bool (and .def_57 .def_63))
(define-fun .def_65 () Bool (and .def_14 .def_64))
(define-fun .def_67 () Bool (! (not .def_65) :invar-property 0))
(assert true)
