(set-info :source |printed by MathSAT|)
(declare-fun |.x{10}| () (Array Int Int))
(declare-fun |.x{14}| () (Array Int Int))
(declare-fun |.x{11}| () Int)
(declare-fun |.y{6}| () Int)
(declare-fun |.x{12}| () Int)
(declare-fun |.y{7}| () Int)
(declare-fun |.y{3}| () (Array Int Int))
(declare-fun |.x{13}| () (Array Int Int))
(declare-fun |.y{4}| () Int)
(declare-fun |.x{15}| () Int)
(declare-fun |.y{5}| () Int)
(declare-fun |.x{16}| () Int)
(declare-fun |.loc{2}| () Bool)
(declare-fun |.loc{3}| () Bool)
(declare-fun |.x{29}| () Int)
(define-fun .def_10 () Int (! |.x{11}| :next |.y{6}|))
(define-fun .def_68 () Bool (= .def_10 0))
(define-fun .def_20 () Bool (! |.loc{2}| :next |.loc{3}|))
(define-fun .def_22 () Bool (not .def_20))
(define-fun .def_69 () Bool (! (and .def_22 .def_68) :init true))
(define-fun .def_8 () (Array Int Int) (! |.x{10}| :next |.x{14}|))
(define-fun .def_64 () Bool (= .def_8 |.x{14}|))
(define-fun .def_65 () Bool (and |.loc{3}| .def_64))
(define-fun .def_12 () Int (! |.x{12}| :next |.y{7}|))
(define-fun .def_61 () Bool (= .def_12 |.x{16}|))
(define-fun .def_59 () Bool (= |.x{15}| 0))
(define-fun .def_23 () Bool (<= .def_12 .def_10))
(define-fun .def_57 () Bool (and .def_22 .def_23))
(define-fun .def_60 () Bool (and .def_57 .def_59))
(define-fun .def_62 () Bool (and .def_60 .def_61))
(define-fun .def_16 () Int (! |.y{4}| :next |.x{15}|))
(define-fun .def_50 () Int (select .def_8 .def_16))
(define-fun .def_51 () Int (* (- 1) .def_50))
(define-fun .def_53 () Int (+ .def_51 1))
(define-fun .def_14 () (Array Int Int) (! |.y{3}| :next |.x{13}|))
(define-fun .def_54 () (Array Int Int) (store .def_14 .def_16 .def_53))
(define-fun .def_55 () Bool (= |.x{13}| .def_54))
(define-fun .def_18 () Int (! |.y{5}| :next |.x{16}|))
(define-fun .def_47 () Bool (<= .def_18 .def_16))
(define-fun .def_48 () Bool (not .def_47))
(define-fun .def_45 () Bool (= .def_18 |.x{16}|))
(define-fun .def_41 () Int (* (- 1) |.x{15}|))
(define-fun .def_42 () Int (+ .def_16 .def_41))
(define-fun .def_43 () Bool (= .def_42 (- 1)))
(define-fun .def_44 () Bool (and .def_20 .def_43))
(define-fun .def_46 () Bool (and .def_44 .def_45))
(define-fun .def_49 () Bool (and .def_46 .def_48))
(define-fun .def_56 () Bool (and .def_49 .def_55))
(define-fun .def_63 () Bool (or .def_56 .def_62))
(define-fun .def_66 () Bool (and .def_63 .def_65))
(define-fun .def_35 () Int (* (- 1) |.y{6}|))
(define-fun .def_36 () Int (+ .def_10 .def_35))
(define-fun .def_37 () Bool (= .def_36 (- 1)))
(define-fun .def_31 () (Array Int Int) (store .def_8 .def_10 1))
(define-fun .def_32 () Bool (= |.x{14}| .def_31))
(define-fun .def_28 () Bool (= .def_12 |.y{7}|))
(define-fun .def_26 () Bool (not |.loc{3}|))
(define-fun .def_24 () Bool (not .def_23))
(define-fun .def_25 () Bool (and .def_22 .def_24))
(define-fun .def_27 () Bool (and .def_25 .def_26))
(define-fun .def_29 () Bool (and .def_27 .def_28))
(define-fun .def_33 () Bool (and .def_29 .def_32))
(define-fun .def_38 () Bool (and .def_33 .def_37))
(define-fun .def_67 () Bool (! (or .def_38 .def_66) :trans true))
(define-fun .def_70 () Int (! |.x{29}| :next |.xpv{1}|))
(define-fun .def_76 () Bool (<= .def_70 0))
(define-fun .def_77 () Bool (not .def_76))
(define-fun .def_78 () Bool (and .def_47 .def_77))
(define-fun .def_74 () Bool (<= .def_18 .def_70))
(define-fun .def_75 () Bool (not .def_74))
(define-fun .def_79 () Bool (and .def_75 .def_78))
(define-fun .def_71 () Int (select .def_14 .def_70))
(define-fun .def_72 () Bool (<= 1 .def_71))
(define-fun .def_73 () Bool (not .def_72))
(define-fun .def_80 () Bool (and .def_73 .def_79))
(define-fun .def_81 () Bool (and .def_20 .def_80))
(define-fun .def_83 () Bool (! (not .def_81) :invar-property 0))
(assert true)
